/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables;


import com.t3h.mysql.Doan;
import com.t3h.mysql.Keys;
import com.t3h.mysql.tables.records.MessageRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message extends TableImpl<MessageRecord> {

    private static final long serialVersionUID = 1643935795;

    /**
     * The reference instance of <code>doan.message</code>
     */
    public static final Message MESSAGE = new Message();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessageRecord> getRecordType() {
        return MessageRecord.class;
    }

    /**
     * The column <code>doan.message.sender_id</code>.
     */
    public final TableField<MessageRecord, String> SENDER_ID = createField("sender_id", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>doan.message.receiver_id</code>.
     */
    public final TableField<MessageRecord, String> RECEIVER_ID = createField("receiver_id", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>doan.message.send_tiem</code>.
     */
    public final TableField<MessageRecord, Date> SEND_TIEM = createField("send_tiem", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>doan.message.content</code>.
     */
    public final TableField<MessageRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>doan.message.img</code>.
     */
    public final TableField<MessageRecord, String> IMG = createField("img", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>doan.message.video</code>.
     */
    public final TableField<MessageRecord, String> VIDEO = createField("video", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>doan.message</code> table reference
     */
    public Message() {
        this("message", null);
    }

    /**
     * Create an aliased <code>doan.message</code> table reference
     */
    public Message(String alias) {
        this(alias, MESSAGE);
    }

    private Message(String alias, Table<MessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Message(String alias, Table<MessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Doan.DOAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MessageRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MessageRecord, ?>>asList(Keys.FK_SENDER_ID, Keys.FK_RECIEVER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Message as(String alias) {
        return new Message(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Message rename(String name) {
        return new Message(name, null);
    }
}
