/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables;


import com.t3h.mysql.Doan;
import com.t3h.mysql.Keys;
import com.t3h.mysql.tables.records.PostRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Post extends TableImpl<PostRecord> {

    private static final long serialVersionUID = 646426230;

    /**
     * The reference instance of <code>doan.post</code>
     */
    public static final Post POST = new Post();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostRecord> getRecordType() {
        return PostRecord.class;
    }

    /**
     * The column <code>doan.post.post_id</code>.
     */
    public final TableField<PostRecord, String> POST_ID = createField("post_id", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>doan.post.userpost_id</code>.
     */
    public final TableField<PostRecord, String> USERPOST_ID = createField("userpost_id", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

    /**
     * The column <code>doan.post.time_post</code>.
     */
    public final TableField<PostRecord, Date> TIME_POST = createField("time_post", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>doan.post.content</code>.
     */
    public final TableField<PostRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>doan.post.img</code>.
     */
    public final TableField<PostRecord, String> IMG = createField("img", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>doan.post.video</code>.
     */
    public final TableField<PostRecord, String> VIDEO = createField("video", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>doan.post</code> table reference
     */
    public Post() {
        this("post", null);
    }

    /**
     * Create an aliased <code>doan.post</code> table reference
     */
    public Post(String alias) {
        this(alias, POST);
    }

    private Post(String alias, Table<PostRecord> aliased) {
        this(alias, aliased, null);
    }

    private Post(String alias, Table<PostRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Doan.DOAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PostRecord> getPrimaryKey() {
        return Keys.KEY_POST_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PostRecord>> getKeys() {
        return Arrays.<UniqueKey<PostRecord>>asList(Keys.KEY_POST_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PostRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PostRecord, ?>>asList(Keys.POST_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Post as(String alias) {
        return new Post(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Post rename(String name) {
        return new Post(name, null);
    }
}
