/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables;


import com.t3h.mysql.Doan;
import com.t3h.mysql.Keys;
import com.t3h.mysql.tables.records.UserRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends TableImpl<UserRecord> {

    private static final long serialVersionUID = -1964537772;

    /**
     * The reference instance of <code>doan.user</code>
     */
    public static final User USER = new User();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserRecord> getRecordType() {
        return UserRecord.class;
    }

    /**
     * The column <code>doan.user.user_id</code>.
     */
    public final TableField<UserRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>doan.user.username</code>.
     */
    public final TableField<UserRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>doan.user.password</code>.
     */
    public final TableField<UserRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

    /**
     * The column <code>doan.user.email</code>.
     */
    public final TableField<UserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>doan.user.avatar</code>.
     */
    public final TableField<UserRecord, String> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>doan.user.birthday</code>.
     */
    public final TableField<UserRecord, Date> BIRTHDAY = createField("birthday", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>doan.user.token</code>.
     */
    public final TableField<UserRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>doan.user.city</code>.
     */
    public final TableField<UserRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(25), this, "");

    /**
     * The column <code>doan.user.job</code>.
     */
    public final TableField<UserRecord, String> JOB = createField("job", org.jooq.impl.SQLDataType.VARCHAR.length(25), this, "");

    /**
     * The column <code>doan.user.sex</code>.
     */
    public final TableField<UserRecord, Boolean> SEX = createField("sex", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * Create a <code>doan.user</code> table reference
     */
    public User() {
        this("user", null);
    }

    /**
     * Create an aliased <code>doan.user</code> table reference
     */
    public User(String alias) {
        this(alias, USER);
    }

    private User(String alias, Table<UserRecord> aliased) {
        this(alias, aliased, null);
    }

    private User(String alias, Table<UserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Doan.DOAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserRecord> getPrimaryKey() {
        return Keys.KEY_USER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserRecord>> getKeys() {
        return Arrays.<UniqueKey<UserRecord>>asList(Keys.KEY_USER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User as(String alias) {
        return new User(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public User rename(String name) {
        return new User(name, null);
    }
}
