/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.records;


import com.t3h.mysql.tables.Message;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends TableRecordImpl<MessageRecord> implements Record6<String, String, Date, String, String, String> {

    private static final long serialVersionUID = 1218447737;

    /**
     * Setter for <code>doan.message.sender_id</code>.
     */
    public void setSenderId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>doan.message.sender_id</code>.
     */
    public String getSenderId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>doan.message.receiver_id</code>.
     */
    public void setReceiverId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>doan.message.receiver_id</code>.
     */
    public String getReceiverId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>doan.message.send_tiem</code>.
     */
    public void setSendTiem(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>doan.message.send_tiem</code>.
     */
    public Date getSendTiem() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>doan.message.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>doan.message.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>doan.message.img</code>.
     */
    public void setImg(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>doan.message.img</code>.
     */
    public String getImg() {
        return (String) get(4);
    }

    /**
     * Setter for <code>doan.message.video</code>.
     */
    public void setVideo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>doan.message.video</code>.
     */
    public String getVideo() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Date, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Date, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Message.MESSAGE.SENDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Message.MESSAGE.RECEIVER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Message.MESSAGE.SEND_TIEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Message.MESSAGE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Message.MESSAGE.IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Message.MESSAGE.VIDEO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSenderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReceiverId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getSendTiem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getVideo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value1(String value) {
        setSenderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value2(String value) {
        setReceiverId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value3(Date value) {
        setSendTiem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value5(String value) {
        setImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord value6(String value) {
        setVideo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MessageRecord values(String value1, String value2, Date value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(String senderId, String receiverId, Date sendTiem, String content, String img, String video) {
        super(Message.MESSAGE);

        set(0, senderId);
        set(1, receiverId);
        set(2, sendTiem);
        set(3, content);
        set(4, img);
        set(5, video);
    }
}
