/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.records;


import com.t3h.mysql.tables.Post;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostRecord extends UpdatableRecordImpl<PostRecord> implements Record6<String, String, Date, String, String, String> {

    private static final long serialVersionUID = 1971659798;

    /**
     * Setter for <code>doan.post.post_id</code>.
     */
    public void setPostId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>doan.post.post_id</code>.
     */
    public String getPostId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>doan.post.userpost_id</code>.
     */
    public void setUserpostId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>doan.post.userpost_id</code>.
     */
    public String getUserpostId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>doan.post.time_post</code>.
     */
    public void setTimePost(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>doan.post.time_post</code>.
     */
    public Date getTimePost() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>doan.post.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>doan.post.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>doan.post.img</code>.
     */
    public void setImg(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>doan.post.img</code>.
     */
    public String getImg() {
        return (String) get(4);
    }

    /**
     * Setter for <code>doan.post.video</code>.
     */
    public void setVideo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>doan.post.video</code>.
     */
    public String getVideo() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Date, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Date, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Post.POST.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Post.POST.USERPOST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Post.POST.TIME_POST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Post.POST.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Post.POST.IMG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Post.POST.VIDEO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserpostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getTimePost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getVideo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value1(String value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value2(String value) {
        setUserpostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value3(Date value) {
        setTimePost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value5(String value) {
        setImg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value6(String value) {
        setVideo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord values(String value1, String value2, Date value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostRecord
     */
    public PostRecord() {
        super(Post.POST);
    }

    /**
     * Create a detached, initialised PostRecord
     */
    public PostRecord(String postId, String userpostId, Date timePost, String content, String img, String video) {
        super(Post.POST);

        set(0, postId);
        set(1, userpostId);
        set(2, timePost);
        set(3, content);
        set(4, img);
        set(5, video);
    }
}
