/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Friends implements Serializable {

    private static final long serialVersionUID = 462734759;

    private String user1Id;
    private String user2Id;
    private Date   timeCreate;

    public Friends() {}

    public Friends(Friends value) {
        this.user1Id = value.user1Id;
        this.user2Id = value.user2Id;
        this.timeCreate = value.timeCreate;
    }

    public Friends(
        String user1Id,
        String user2Id,
        Date   timeCreate
    ) {
        this.user1Id = user1Id;
        this.user2Id = user2Id;
        this.timeCreate = timeCreate;
    }

    public String getUser1Id() {
        return this.user1Id;
    }

    public void setUser1Id(String user1Id) {
        this.user1Id = user1Id;
    }

    public String getUser2Id() {
        return this.user2Id;
    }

    public void setUser2Id(String user2Id) {
        this.user2Id = user2Id;
    }

    public Date getTimeCreate() {
        return this.timeCreate;
    }

    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Friends (");

        sb.append(user1Id);
        sb.append(", ").append(user2Id);
        sb.append(", ").append(timeCreate);

        sb.append(")");
        return sb.toString();
    }
}
