/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message implements Serializable {

    private static final long serialVersionUID = 1621704929;

    private String senderId;
    private String receiverId;
    private Date   sendTiem;
    private String content;
    private String img;
    private String video;

    public Message() {}

    public Message(Message value) {
        this.senderId = value.senderId;
        this.receiverId = value.receiverId;
        this.sendTiem = value.sendTiem;
        this.content = value.content;
        this.img = value.img;
        this.video = value.video;
    }

    public Message(
        String senderId,
        String receiverId,
        Date   sendTiem,
        String content,
        String img,
        String video
    ) {
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.sendTiem = sendTiem;
        this.content = content;
        this.img = img;
        this.video = video;
    }

    public String getSenderId() {
        return this.senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getReceiverId() {
        return this.receiverId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public Date getSendTiem() {
        return this.sendTiem;
    }

    public void setSendTiem(Date sendTiem) {
        this.sendTiem = sendTiem;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImg() {
        return this.img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getVideo() {
        return this.video;
    }

    public void setVideo(String video) {
        this.video = video;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(senderId);
        sb.append(", ").append(receiverId);
        sb.append(", ").append(sendTiem);
        sb.append(", ").append(content);
        sb.append(", ").append(img);
        sb.append(", ").append(video);

        sb.append(")");
        return sb.toString();
    }
}
