/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Post implements Serializable {

    private static final long serialVersionUID = 1503293340;

    private String postId;
    private String userpostId;
    private Date   timePost;
    private String content;
    private String img;
    private String video;

    public Post() {}

    public Post(Post value) {
        this.postId = value.postId;
        this.userpostId = value.userpostId;
        this.timePost = value.timePost;
        this.content = value.content;
        this.img = value.img;
        this.video = value.video;
    }

    public Post(
        String postId,
        String userpostId,
        Date   timePost,
        String content,
        String img,
        String video
    ) {
        this.postId = postId;
        this.userpostId = userpostId;
        this.timePost = timePost;
        this.content = content;
        this.img = img;
        this.video = video;
    }

    public String getPostId() {
        return this.postId;
    }

    public void setPostId(String postId) {
        this.postId = postId;
    }

    public String getUserpostId() {
        return this.userpostId;
    }

    public void setUserpostId(String userpostId) {
        this.userpostId = userpostId;
    }

    public Date getTimePost() {
        return this.timePost;
    }

    public void setTimePost(Date timePost) {
        this.timePost = timePost;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImg() {
        return this.img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getVideo() {
        return this.video;
    }

    public void setVideo(String video) {
        this.video = video;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Post (");

        sb.append(postId);
        sb.append(", ").append(userpostId);
        sb.append(", ").append(timePost);
        sb.append(", ").append(content);
        sb.append(", ").append(img);
        sb.append(", ").append(video);

        sb.append(")");
        return sb.toString();
    }
}
