/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -367261505;

    private String  userId;
    private String  username;
    private String  password;
    private String  email;
    private String  avatar;
    private Date    birthday;
    private String  token;
    private String  city;
    private String  job;
    private Boolean sex;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.username = value.username;
        this.password = value.password;
        this.email = value.email;
        this.avatar = value.avatar;
        this.birthday = value.birthday;
        this.token = value.token;
        this.city = value.city;
        this.job = value.job;
        this.sex = value.sex;
    }

    public User(
        String  userId,
        String  username,
        String  password,
        String  email,
        String  avatar,
        Date    birthday,
        String  token,
        String  city,
        String  job,
        Boolean sex
    ) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.email = email;
        this.avatar = avatar;
        this.birthday = birthday;
        this.token = token;
        this.city = city;
        this.job = job;
        this.sex = sex;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getJob() {
        return this.job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public Boolean getSex() {
        return this.sex;
    }

    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(avatar);
        sb.append(", ").append(birthday);
        sb.append(", ").append(token);
        sb.append(", ").append(city);
        sb.append(", ").append(job);
        sb.append(", ").append(sex);

        sb.append(")");
        return sb.toString();
    }
}
