/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql;


import com.t3h.mysql.tables.Friends;
import com.t3h.mysql.tables.Message;
import com.t3h.mysql.tables.Post;
import com.t3h.mysql.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doan extends SchemaImpl {

    private static final long serialVersionUID = 409577679;

    /**
     * The reference instance of <code>doan</code>
     */
    public static final Doan DOAN = new Doan();

    /**
     * The table <code>doan.friends</code>.
     */
    public final Friends FRIENDS = com.t3h.mysql.tables.Friends.FRIENDS;

    /**
     * The table <code>doan.message</code>.
     */
    public final Message MESSAGE = com.t3h.mysql.tables.Message.MESSAGE;

    /**
     * The table <code>doan.post</code>.
     */
    public final Post POST = com.t3h.mysql.tables.Post.POST;

    /**
     * The table <code>doan.user</code>.
     */
    public final User USER = com.t3h.mysql.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Doan() {
        super("doan", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Friends.FRIENDS,
            Message.MESSAGE,
            Post.POST,
            User.USER);
    }
}
