/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql;


import com.t3h.mysql.tables.Friends;
import com.t3h.mysql.tables.Message;
import com.t3h.mysql.tables.Post;
import com.t3h.mysql.tables.User;
import com.t3h.mysql.tables.records.FriendsRecord;
import com.t3h.mysql.tables.records.MessageRecord;
import com.t3h.mysql.tables.records.PostRecord;
import com.t3h.mysql.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>doan</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FriendsRecord> KEY_FRIENDS_PRIMARY = UniqueKeys0.KEY_FRIENDS_PRIMARY;
    public static final UniqueKey<PostRecord> KEY_POST_PRIMARY = UniqueKeys0.KEY_POST_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<FriendsRecord, UserRecord> FK_USER1_FRIEND = ForeignKeys0.FK_USER1_FRIEND;
    public static final ForeignKey<FriendsRecord, UserRecord> FL_USER2_FRIEND = ForeignKeys0.FL_USER2_FRIEND;
    public static final ForeignKey<MessageRecord, UserRecord> FK_SENDER_ID = ForeignKeys0.FK_SENDER_ID;
    public static final ForeignKey<MessageRecord, UserRecord> FK_RECIEVER_ID = ForeignKeys0.FK_RECIEVER_ID;
    public static final ForeignKey<PostRecord, UserRecord> POST_FK = ForeignKeys0.POST_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<FriendsRecord> KEY_FRIENDS_PRIMARY = createUniqueKey(Friends.FRIENDS, "KEY_friends_PRIMARY", Friends.FRIENDS.USER1_ID, Friends.FRIENDS.USER2_ID);
        public static final UniqueKey<PostRecord> KEY_POST_PRIMARY = createUniqueKey(Post.POST, "KEY_post_PRIMARY", Post.POST.POST_ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.USER_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<FriendsRecord, UserRecord> FK_USER1_FRIEND = createForeignKey(com.t3h.mysql.Keys.KEY_USER_PRIMARY, Friends.FRIENDS, "fk_user1_friend", Friends.FRIENDS.USER1_ID);
        public static final ForeignKey<FriendsRecord, UserRecord> FL_USER2_FRIEND = createForeignKey(com.t3h.mysql.Keys.KEY_USER_PRIMARY, Friends.FRIENDS, "fl_user2_friend", Friends.FRIENDS.USER2_ID);
        public static final ForeignKey<MessageRecord, UserRecord> FK_SENDER_ID = createForeignKey(com.t3h.mysql.Keys.KEY_USER_PRIMARY, Message.MESSAGE, "fk_sender_id", Message.MESSAGE.SENDER_ID);
        public static final ForeignKey<MessageRecord, UserRecord> FK_RECIEVER_ID = createForeignKey(com.t3h.mysql.Keys.KEY_USER_PRIMARY, Message.MESSAGE, "fk-reciever_id", Message.MESSAGE.RECEIVER_ID);
        public static final ForeignKey<PostRecord, UserRecord> POST_FK = createForeignKey(com.t3h.mysql.Keys.KEY_USER_PRIMARY, Post.POST, "post_fk", Post.POST.USERPOST_ID);
    }
}
