/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql;


import com.t3h.mysql.tables.Friends;
import com.t3h.mysql.tables.Message;
import com.t3h.mysql.tables.Post;
import com.t3h.mysql.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in doan
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>doan.friends</code>.
     */
    public static final Friends FRIENDS = com.t3h.mysql.tables.Friends.FRIENDS;

    /**
     * The table <code>doan.message</code>.
     */
    public static final Message MESSAGE = com.t3h.mysql.tables.Message.MESSAGE;

    /**
     * The table <code>doan.post</code>.
     */
    public static final Post POST = com.t3h.mysql.tables.Post.POST;

    /**
     * The table <code>doan.user</code>.
     */
    public static final User USER = com.t3h.mysql.tables.User.USER;
}
