/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.daos;


import com.t3h.mysql.tables.Friends;
import com.t3h.mysql.tables.records.FriendsRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FriendsDao extends DAOImpl<FriendsRecord, com.t3h.mysql.tables.pojos.Friends, Record2<String, String>> {

    /**
     * Create a new FriendsDao without any configuration
     */
    public FriendsDao() {
        super(Friends.FRIENDS, com.t3h.mysql.tables.pojos.Friends.class);
    }

    /**
     * Create a new FriendsDao with an attached configuration
     */
    public FriendsDao(Configuration configuration) {
        super(Friends.FRIENDS, com.t3h.mysql.tables.pojos.Friends.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(com.t3h.mysql.tables.pojos.Friends object) {
        return compositeKeyRecord(object.getUser1Id(), object.getUser2Id());
    }

    /**
     * Fetch records that have <code>user1_id IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Friends> fetchByUser1Id(String... values) {
        return fetch(Friends.FRIENDS.USER1_ID, values);
    }

    /**
     * Fetch records that have <code>user2_id IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Friends> fetchByUser2Id(String... values) {
        return fetch(Friends.FRIENDS.USER2_ID, values);
    }

    /**
     * Fetch records that have <code>time_create IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Friends> fetchByTimeCreate(Date... values) {
        return fetch(Friends.FRIENDS.TIME_CREATE, values);
    }
}
