/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.daos;


import com.t3h.mysql.tables.Post;
import com.t3h.mysql.tables.records.PostRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostDao extends DAOImpl<PostRecord, com.t3h.mysql.tables.pojos.Post, String> {

    /**
     * Create a new PostDao without any configuration
     */
    public PostDao() {
        super(Post.POST, com.t3h.mysql.tables.pojos.Post.class);
    }

    /**
     * Create a new PostDao with an attached configuration
     */
    public PostDao(Configuration configuration) {
        super(Post.POST, com.t3h.mysql.tables.pojos.Post.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.t3h.mysql.tables.pojos.Post object) {
        return object.getPostId();
    }

    /**
     * Fetch records that have <code>post_id IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Post> fetchByPostId(String... values) {
        return fetch(Post.POST.POST_ID, values);
    }

    /**
     * Fetch a unique record that has <code>post_id = value</code>
     */
    public com.t3h.mysql.tables.pojos.Post fetchOneByPostId(String value) {
        return fetchOne(Post.POST.POST_ID, value);
    }

    /**
     * Fetch records that have <code>userpost_id IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Post> fetchByUserpostId(String... values) {
        return fetch(Post.POST.USERPOST_ID, values);
    }

    /**
     * Fetch records that have <code>time_post IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Post> fetchByTimePost(Date... values) {
        return fetch(Post.POST.TIME_POST, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Post> fetchByContent(String... values) {
        return fetch(Post.POST.CONTENT, values);
    }

    /**
     * Fetch records that have <code>img IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Post> fetchByImg(String... values) {
        return fetch(Post.POST.IMG, values);
    }

    /**
     * Fetch records that have <code>video IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.Post> fetchByVideo(String... values) {
        return fetch(Post.POST.VIDEO, values);
    }
}
