/*
 * This file is generated by jOOQ.
*/
package com.t3h.mysql.tables.daos;


import com.t3h.mysql.tables.User;
import com.t3h.mysql.tables.records.UserRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, com.t3h.mysql.tables.pojos.User, String> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.t3h.mysql.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, com.t3h.mysql.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.t3h.mysql.tables.pojos.User object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByUserId(String... values) {
        return fetch(User.USER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.t3h.mysql.tables.pojos.User fetchOneByUserId(String value) {
        return fetchOne(User.USER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByPassword(String... values) {
        return fetch(User.USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByEmail(String... values) {
        return fetch(User.USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>avatar IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByAvatar(String... values) {
        return fetch(User.USER.AVATAR, values);
    }

    /**
     * Fetch records that have <code>birthday IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByBirthday(Date... values) {
        return fetch(User.USER.BIRTHDAY, values);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByToken(String... values) {
        return fetch(User.USER.TOKEN, values);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByCity(String... values) {
        return fetch(User.USER.CITY, values);
    }

    /**
     * Fetch records that have <code>job IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchByJob(String... values) {
        return fetch(User.USER.JOB, values);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<com.t3h.mysql.tables.pojos.User> fetchBySex(Boolean... values) {
        return fetch(User.USER.SEX, values);
    }
}
